export type UILanguage = "en" | "bn" | "az" | "hi" | "ky" | "tg" | "uz" | "ur" | "ar" | "tr";

export interface LanguageOption {
  code: UILanguage;
  country: string;
  nativeName: string;
  englishName: string;
  flag: string;
}

// Right-to-left scripts (Urdu Nastaliq + Arabic). Used to flip layout direction.
export const RTL_LANGS = new Set<UILanguage>(["ur", "ar"]);
export function isRTL(lang: UILanguage): boolean { return RTL_LANGS.has(lang); }

// Order: English (default) first, then Bangladesh, then others alphabetically by country.
export const LANGUAGES: LanguageOption[] = [
  { code: "en", country: "International", nativeName: "English",       englishName: "English",      flag: "🌐" },
  { code: "bn", country: "Bangladesh",    nativeName: "বাংলা",          englishName: "Bengali",      flag: "🇧🇩" },
  { code: "az", country: "Azerbaijan",    nativeName: "Azərbaycanca",   englishName: "Azerbaijani",  flag: "🇦🇿" },
  { code: "hi", country: "India",         nativeName: "हिन्दी",          englishName: "Hindi",        flag: "🇮🇳" },
  { code: "ky", country: "Kyrgyzstan",    nativeName: "Кыргызча",       englishName: "Kyrgyz",       flag: "🇰🇬" },
  { code: "ar", country: "Morocco",       nativeName: "العربية",         englishName: "Arabic",       flag: "🇲🇦" },
  { code: "ur", country: "Pakistan",      nativeName: "اُردُو",          englishName: "Urdu",         flag: "🇵🇰" },
  { code: "tg", country: "Tajikistan",    nativeName: "Тоҷикӣ",          englishName: "Tajik",        flag: "🇹🇯" },
  { code: "tr", country: "Turkey",        nativeName: "Türkçe",          englishName: "Turkish",      flag: "🇹🇷" },
  { code: "uz", country: "Uzbekistan",    nativeName: "Oʻzbekcha",       englishName: "Uzbek",        flag: "🇺🇿" },
];

// English is the source of truth and the universal fallback. The other
// languages are optional — anything missing falls back to English at lookup
// time via t(). This keeps types strict without requiring all 150+ strings
// to be hand-translated for every newly added language up-front.
type Dict = Partial<Record<UILanguage, string>> & { en: string };

// Master translation table. Keys grouped by namespace for readability.
export const T = {
  // ---------- Navbar / common ----------
  search:        { en: "Search...",   bn: "খুঁজুন...",          az: "Axtarış...",   hi: "खोजें...",      ky: "Издөө...",      tg: "Ҷустуҷӯ...",   uz: "Qidirish...",         ur: "تلاش کریں...",    ar: "بحث...",          tr: "Ara..." },
  flashcards:    { en: "Flashcards",  bn: "ফ্ল্যাশকার্ড",       az: "Flaşkartlar",  hi: "फ्लैशकार्ड",      ky: "Карточкалар",   tg: "Кортҳои хотиравӣ", uz: "Flashkartalar" },
  vocabulary:    { en: "Vocabulary",  bn: "শব্দ ভাণ্ডার",         az: "Lüğət",        hi: "शब्दावली",       ky: "Сөздүк",        tg: "Луғат",          uz: "Lugʻat" },
  lessons:       { en: "Lessons",     bn: "পাঠ",               az: "Dərslər",      hi: "पाठ",          ky: "Сабактар",      tg: "Дарсҳо",         uz: "Darslar" },
  examPrep:      { en: "Exam Prep",   bn: "পরীক্ষার প্রস্তুতি", az: "İmtahana hazırlıq", hi: "परीक्षा की तैयारी", ky: "Сынакка даярдык", tg: "Омодагӣ ба имтиҳон", uz: "Imtihonga tayyorgarlik" },
  dashboard:     { en: "Dashboard",   bn: "ড্যাশবোর্ড",         az: "İdarə paneli", hi: "डैशबोर्ड",       ky: "Башкаруу панели", tg: "Лавҳаи идора",  uz: "Boshqaruv paneli" },
  profile:       { en: "Profile",     bn: "প্রোফাইল",           az: "Profil",       hi: "प्रोफ़ाइल",      ky: "Профиль",       tg: "Профил",         uz: "Profil" },
  signIn:        { en: "Sign In",     bn: "লগইন",              az: "Daxil ol",     hi: "साइन इन",      ky: "Кирүү",         tg: "Воридшавӣ",      uz: "Kirish" },
  signOut:       { en: "Sign Out",    bn: "লগ আউট",            az: "Çıxış",        hi: "साइन आउट",     ky: "Чыгуу",         tg: "Баромадан",      uz: "Chiqish" },
  signUp:        { en: "Sign Up",     bn: "রেজিস্ট্রেশন",       az: "Qeydiyyat",    hi: "साइन अप",      ky: "Катталуу",      tg: "Сабти ном",      uz: "Roʻyxatdan oʻtish" },
  language:      { en: "Language",    bn: "ভাষা",               az: "Dil",          hi: "भाषा",         ky: "Тил",           tg: "Забон",          uz: "Til" },
  quizzes:       { en: "Quizzes",     bn: "কুইজ",               az: "Testlər",      hi: "क्विज़",         ky: "Тесттер",       tg: "Тестҳо",         uz: "Testlar" },
  grammar:       { en: "Grammar",     bn: "ব্যাকরণ",            az: "Qrammatika",   hi: "व्याकरण",       ky: "Грамматика",    tg: "Грамматика",    uz: "Grammatika" },
  fundamentals:  { en: "Fundamentals", bn: "মূল বিষয়",         az: "Əsaslar",      hi: "मूल बातें",      ky: "Негиздер",      tg: "Асосҳо",        uz: "Asoslar" },
  dialogues:     { en: "Dialogues",   bn: "কথোপকথন",          az: "Dialoqlar",    hi: "संवाद",         ky: "Диалогдор",     tg: "Муколамаҳо",    uz: "Dialoglar" },
  reading:       { en: "Reading",     bn: "পড়া",               az: "Oxu",          hi: "पठन",         ky: "Окуу",          tg: "Хониш",         uz: "Oʻqish" },
  writing:       { en: "Writing",     bn: "লেখা",               az: "Yazı",         hi: "लेखन",         ky: "Жазуу",         tg: "Навиштан",      uz: "Yozish" },
  listening:     { en: "Listening",   bn: "শোনা",               az: "Dinləmə",      hi: "श्रवण",        ky: "Угуу",          tg: "Гӯш кардан",    uz: "Tinglash" },
  speaking:      { en: "Speaking",    bn: "বলা",                az: "Danışıq",      hi: "बोलना",        ky: "Сүйлөө",        tg: "Гуфтор",        uz: "Soʻzlash" },

  // ---------- Generic actions / labels ----------
  start:         { en: "Get Started",       bn: "শুরু করুন",         az: "Başla",        hi: "शुरू करें",      ky: "Баштоо",        tg: "Оғоз кунед",    uz: "Boshlash" },
  startNow:      { en: "Start Now",         bn: "এখনই শুরু করুন",    az: "İndi başla",   hi: "अभी शुरू करें",  ky: "Дароо баштоо",  tg: "Ҳозир оғоз кунед", uz: "Hozir boshlash" },
  continue:      { en: "Continue",          bn: "চালিয়ে যান",       az: "Davam et",     hi: "जारी रखें",      ky: "Улантуу",       tg: "Идома диҳед",   uz: "Davom etish" },
  viewAll:       { en: "View All",          bn: "সব দেখুন",           az: "Hamısına bax", hi: "सभी देखें",      ky: "Бардыгын көрүү", tg: "Ҳамаро бинед", uz: "Hammasini koʻrish" },
  viewDemo:      { en: "View Demo",         bn: "ডেমো দেখুন",         az: "Demo bax",     hi: "डेमो देखें",     ky: "Демо көрүү",    tg: "Демо бинед",    uz: "Demo koʻrish" },
  loading:       { en: "Loading...",        bn: "লোড হচ্ছে...",       az: "Yüklənir...",  hi: "लोड हो रहा है...", ky: "Жүктөлүүдө...", tg: "Боргузорӣ...", uz: "Yuklanmoqda..." },
  cancel:        { en: "Cancel",            bn: "বাতিল",              az: "Ləğv et",      hi: "रद्द करें",      ky: "Жокко чыгаруу", tg: "Бекор кардан",  uz: "Bekor qilish" },
  save:          { en: "Save",              bn: "সংরক্ষণ",            az: "Yadda saxla",  hi: "सहेजें",        ky: "Сактоо",        tg: "Захира кардан", uz: "Saqlash" },
  next:          { en: "Next",              bn: "পরবর্তী",            az: "Növbəti",      hi: "अगला",         ky: "Кийинки",       tg: "Навбатӣ",       uz: "Keyingi" },
  previous:      { en: "Previous",          bn: "পূর্ববর্তী",          az: "Əvvəlki",      hi: "पिछला",        ky: "Мурунку",       tg: "Гузашта",       uz: "Oldingi" },
  submit:        { en: "Submit",            bn: "জমা দিন",            az: "Göndər",       hi: "जमा करें",       ky: "Жөнөтүү",       tg: "Фиристодан",    uz: "Yuborish" },
  retry:         { en: "Try Again",         bn: "আবার চেষ্টা করুন",   az: "Yenidən cəhd", hi: "फिर कोशिश करें", ky: "Кайра аракет",  tg: "Боз кӯшиш",     uz: "Qayta urinish" },
  noResults:     { en: "No results found",  bn: "কোনো ফলাফল পাওয়া যায়নি", az: "Nəticə tapılmadı", hi: "कोई परिणाम नहीं मिला", ky: "Эч нерсе табылган жок", tg: "Натиҷа ёфт нашуд", uz: "Natija topilmadi" },
  free:          { en: "Free",              bn: "বিনামূল্যে",         az: "Pulsuz",       hi: "मुफ़्त",         ky: "Акысыз",        tg: "Ройгон",        uz: "Bepul" },
  complete:      { en: "complete",          bn: "সম্পন্ন",            az: "tamamlandı",   hi: "पूर्ण",         ky: "аяктады",       tg: "ба итмом расид", uz: "tugatildi" },
  noun:          { en: "noun",              bn: "বিশেষ্য",            az: "isim",         hi: "संज्ञा",        ky: "зат атооч",     tg: "исм",           uz: "ot" },
  verb:          { en: "verb",              bn: "ক্রিয়া",            az: "fel",          hi: "क्रिया",        ky: "этиш",          tg: "феъл",          uz: "feʼl" },
  adjective:     { en: "adjective",         bn: "বিশেষণ",             az: "sifət",        hi: "विशेषण",        ky: "сын атооч",     tg: "сифат",         uz: "sifat" },
  adverb:        { en: "adverb",            bn: "ক্রিয়া বিশেষণ",      az: "zərf",         hi: "क्रिया विशेषण",  ky: "тактооч",       tg: "зарф",          uz: "ravish" },
  masc:          { en: "masc.",             bn: "পুংলিঙ্গ",           az: "kişi cinsi",   hi: "पुल्लिंग",      ky: "эркек",         tg: "мардона",       uz: "erkak" },
  fem:           { en: "fem.",              bn: "স্ত্রীলিঙ্গ",         az: "qadın cinsi",  hi: "स्त्रीलिंग",     ky: "аял",           tg: "занона",        uz: "ayol" },

  // ---------- Homepage ----------
  homeBadge:     { en: "Lithuanian language for international learners", bn: "আন্তর্জাতিক শিক্ষার্থীদের জন্য লিথুয়ানিয়ান ভাষা", az: "Beynəlxalq tələbələr üçün Litva dili", hi: "अंतरराष्ट्रीय छात्रों के लिए लिथुआनियाई भाषा", ky: "Эл аралык окуучулар үчүн литва тили", tg: "Забони литвагӣ барои донишҷӯёни байналмилалӣ", uz: "Xalqaro talabalar uchun litva tili" },
  homeHero1:     { en: "Learn Lithuanian",                bn: "লিথুয়ানিয়ান শিখুন",   az: "Litva dilini öyrənin", hi: "लिथुआनियाई सीखें",  ky: "Литва тилин үйрөнүңүз", tg: "Забони литвагиро омӯзед", uz: "Litva tilini oʻrganing" },
  homeHero2:     { en: "the easy way",                    bn: "সহজে",                  az: "asan yolla",       hi: "आसान तरीके से",  ky: "оңой жол менен", tg: "ба тариқи осон",  uz: "oson yoʻl bilan" },
  homeSubtitle1: { en: "Every word — with translation and audio", bn: "প্রতিটি শব্দ — অনুবাদ ও অডিওসহ", az: "Hər söz — tərcümə və səslə", hi: "हर शब्द — अनुवाद और ऑडियो के साथ", ky: "Ар бир сөз — котормосу жана үнү менен", tg: "Ҳар калима — бо тарҷума ва аудио", uz: "Har bir soʻz — tarjima va audio bilan" },
  homeSubtitle2: { en: "Learn Lithuanian with explanations in your language, native audio on every word, and complete A1 exam preparation.", bn: "আপনার ভাষায় ব্যাখ্যাসহ লিথুয়ানিয়ান শিখুন, প্রতিটি শব্দে স্থানীয় অডিও, এবং সম্পূর্ণ A1 পরীক্ষার প্রস্তুতি।", az: "Öz dilinizdə izahlarla, hər sözdə doğma səslə və tam A1 imtahan hazırlığı ilə Litva dilini öyrənin.", hi: "अपनी भाषा में व्याख्या के साथ लिथुआनियाई सीखें, हर शब्द पर मूल ऑडियो और पूर्ण A1 परीक्षा की तैयारी।", ky: "Литва тилин өз тилиңиздеги түшүндүрмөлөр, ар бир сөздөгү жергиликтүү үн жана толук A1 сынагына даярдык менен үйрөнүңүз.", tg: "Забони литвагиро бо шарҳҳо ба забони худ, аудиои аслӣ дар ҳар калима ва омодагии пурраи имтиҳони A1 омӯзед.", uz: "Litva tilini oʻz tilingizdagi izohlar, har bir soʻzdagi mahalliy audio va toʻliq A1 imtihon tayyorgarligi bilan oʻrganing." },
  homeWhy:       { en: "Why",                              bn: "কেন",                   az: "Niyə",             hi: "क्यों",          ky: "Эмне үчүн",     tg: "Чаро",          uz: "Nega" },
  homeWhySub:    { en: "Why choose KalbaLab?",         bn: "কেন KalbaLab বেছে নেবেন?", az: "Niyə KalbaLab?", hi: "KalbaLab क्यों चुनें?", ky: "Эмне үчүн KalbaLab?", tg: "Чаро KalbaLab?", uz: "Nega KalbaLab?" },
  feat1Title:    { en: "Audio on Everything",              bn: "সব কিছুতে অডিও",        az: "Hər şeydə səs",    hi: "हर चीज़ पर ऑडियो", ky: "Бардык нерседе үн", tg: "Аудио дар ҳама ҷо", uz: "Hammasida audio" },
  feat1Desc:     { en: "Speaker button on every word and sentence — hear native Lithuanian pronunciation.", bn: "প্রতিটি শব্দ ও বাক্যে স্পিকার বাটন — লিথুয়ানিয়ান উচ্চারণ শুনুন।", az: "Hər söz və cümlədə səs düyməsi — doğma Litva tələffüzünü dinləyin.", hi: "हर शब्द और वाक्य पर स्पीकर बटन — मूल लिथुआनियाई उच्चारण सुनें।", ky: "Ар бир сөз жана сүйлөмдө үн баскычы — түпкүлүктүү литва айтылышын угуңуз.", tg: "Тугмаи садо дар ҳар калима ва ҷумла — талаффузи аслии литвагиро гӯш кунед.", uz: "Har bir soʻz va jumlada karnay tugmasi — asl litva talaffuzini eshiting." },
  feat2Title:    { en: "Native Language Explanations",     bn: "মাতৃভাষায় ব্যাখ্যা",   az: "Ana dilində izahlar", hi: "मातृभाषा में व्याख्या", ky: "Эне тилдеги түшүндүрмөлөр", tg: "Шарҳҳо ба забони модарӣ", uz: "Ona tilida izohlar" },
  feat2Desc:     { en: "Grammar, vocabulary and notes in your own language — learn in the language you think in.", bn: "ব্যাকরণ, শব্দ ও ব্যাখ্যা আপনার ভাষায় — যে ভাষায় চিন্তা করেন সেই ভাষায় শিখুন।", az: "Qrammatika, lüğət və qeydlər öz dilinizdə — düşündüyünüz dildə öyrənin.", hi: "व्याकरण, शब्दावली और नोट्स आपकी भाषा में — जिस भाषा में सोचते हैं उसी में सीखें।", ky: "Грамматика, сөздүк жана эскертүүлөр өз тилиңизде — ойлогон тилиңизде үйрөнүңүз.", tg: "Грамматика, луғат ва қайдҳо ба забони худатон — ба забоне ки фикр мекунед омӯзед.", uz: "Grammatika, lugʻat va izohlar oʻz tilingizda — qaysi tilda fikrlasangiz, oʻsha tilda oʻrganing." },
  feat3Title:    { en: "A1 Exam Preparation",              bn: "A1 পরীক্ষার প্রস্তুতি", az: "A1 imtahan hazırlığı", hi: "A1 परीक्षा की तैयारी", ky: "A1 сынак даярдыгы", tg: "Омодагии имтиҳони A1", uz: "A1 imtihon tayyorgarligi" },
  feat3Desc:     { en: "Complete preparation course for the Lithuanian residency exam.", bn: "লিথুয়ানিয়ার আবাসিক পরীক্ষার জন্য সম্পূর্ণ প্রস্তুতি কোর্স।", az: "Litva yaşayış icazəsi imtahanı üçün tam hazırlıq kursu.", hi: "लिथुआनियाई निवास परीक्षा के लिए पूर्ण तैयारी पाठ्यक्रम।", ky: "Литва жашоо уруксаты сынагы үчүн толук даярдык курсу.", tg: "Курси пурраи омодагӣ барои имтиҳони иҷозати истиқомат дар Литва.", uz: "Litva yashash ruxsatnomasi imtihoni uchun toʻliq tayyorgarlik kursi." },
  feat4Title:    { en: "500+ Vocabulary Words",            bn: "৫০০+ শব্দ ভাণ্ডার",      az: "500+ lüğət sözü",  hi: "500+ शब्दावली",  ky: "500+ сөз",     tg: "500+ калима",  uz: "500+ soʻz" },
  feat4Desc:     { en: "All essential A1-level words with audio and translations.", bn: "A1 স্তরের সব গুরুত্বপূর্ণ শব্দ অডিও ও অনুবাদসহ।", az: "Bütün vacib A1 səviyyəli sözlər səs və tərcümə ilə.", hi: "सभी आवश्यक A1 स्तर के शब्द ऑडियो और अनुवाद के साथ।", ky: "Бардык маанилүү A1 деңгээлиндеги сөздөр үн жана котормо менен.", tg: "Ҳамаи калимаҳои зарурии сатҳи A1 бо аудио ва тарҷума.", uz: "Barcha muhim A1 darajasidagi soʻzlar audio va tarjima bilan." },
  feat5Title:    { en: "Real-Life Dialogues",              bn: "বাস্তব কথোপকথন",       az: "Real həyat dialoqları", hi: "वास्तविक संवाद", ky: "Реалдуу диалогдор", tg: "Муколамаҳои воқеӣ", uz: "Hayotiy dialoglar" },
  feat5Desc:     { en: "Shop, hospital, street — dialogues for real situations.", bn: "দোকানে, হাসপাতালে, রাস্তায় — বাস্তব পরিস্থিতির কথোপকথন।", az: "Mağaza, xəstəxana, küçə — real situasiyalar üçün dialoqlar.", hi: "दुकान, अस्पताल, सड़क — वास्तविक स्थितियों के लिए संवाद।", ky: "Дүкөн, оорукана, көчө — реалдуу кырдаалдар үчүн диалогдор.", tg: "Дӯкон, беморхона, кӯча — муколамаҳо барои вазъиятҳои воқеӣ.", uz: "Doʻkon, kasalxona, koʻcha — haqiqiy vaziyatlar uchun dialoglar." },
  feat6Title:    { en: "Progress Tracking",                bn: "অগ্রগতি ট্র্যাকিং",     az: "İrəliləyiş izləməsi", hi: "प्रगति ट्रैकिंग",  ky: "Прогрессти көзөмөлдөө", tg: "Пайгирии пешрафт", uz: "Taraqqiyotni kuzatish" },
  feat6Desc:     { en: "Spaced repetition + XP system + daily streaks.", bn: "স্পেসড রিপিটিশন + XP সিস্টেম + ধারাবাহিক স্ট্রিক।", az: "Aralıqlı təkrar + XP sistemi + gündəlik silsilələr.", hi: "स्पेस्ड रिपीटिशन + XP सिस्टम + दैनिक स्ट्रीक।", ky: "Аралыктуу кайталоо + XP системасы + күнүмдүк катар.", tg: "Такрори фосиладор + системаи XP + силсилаҳои ҳаррӯза.", uz: "Oraliqli takrorlash + XP tizimi + kunlik ketma-ketlik." },
  trySample:     { en: "Try a sample flashcard",           bn: "একটি ফ্ল্যাশকার্ড দেখুন", az: "Nümunə flaşkartı sınayın", hi: "एक नमूना फ्लैशकार्ड आज़माएँ", ky: "Үлгү карточкасын сынап көрүңүз", tg: "Корти намунавиро санҷед", uz: "Namuna flashkartani sinab koʻring" },
  trySampleSub:  { en: "No login required",                bn: "লগইন লাগবে না",         az: "Giriş tələb olunmur", hi: "लॉगिन आवश्यक नहीं", ky: "Кирүү талап кылынбайт", tg: "Воридшавӣ лозим нест", uz: "Kirish talab qilinmaydi" },
  viewAllFlash:  { en: "View all flashcards",              bn: "সব ফ্ল্যাশকার্ড দেখুন",  az: "Bütün flaşkartlara bax", hi: "सभी फ्लैशकार्ड देखें", ky: "Бардык карточкаларды көрүү", tg: "Ҳамаи кортҳоро бинед", uz: "Barcha flashkartalarni koʻrish" },
  examTitle:     { en: "🎓 A1 Exam Preparation",           bn: "🎓 A1 পরীক্ষার প্রস্তুতি", az: "🎓 A1 imtahan hazırlığı", hi: "🎓 A1 परीक्षा की तैयारी", ky: "🎓 A1 сынак даярдыгы", tg: "🎓 Омодагии имтиҳони A1", uz: "🎓 A1 imtihon tayyorgarligi" },
  examSubtitle:  { en: "A1 Lithuanian Language Exam (Integration Test)", bn: "A1 লিথুয়ানিয়ান ভাষা পরীক্ষা (ইন্টিগ্রেশন টেস্ট)", az: "A1 Litva Dili İmtahanı (İnteqrasiya Testi)", hi: "A1 लिथुआनियाई भाषा परीक्षा (एकीकरण परीक्षण)", ky: "A1 Литва тил сынагы (Интеграциялык тест)", tg: "Имтиҳони забони литвагии A1 (Тести ҳамгироӣ)", uz: "A1 Litva tili imtihoni (Integratsiya testi)" },
  examFee:       { en: "Fee:",                             bn: "ফি:",                    az: "Ödəniş:",          hi: "शुल्क:",         ky: "Акы:",          tg: "Пардохт:",       uz: "Toʻlov:" },
  examPass:      { en: "Pass:",                            bn: "পাস:",                   az: "Keçid:",           hi: "उत्तीर्ण:",      ky: "Өтүү:",         tg: "Гузаштан:",      uz: "Oʻtish:" },
  overall:       { en: "overall",                          bn: "সামগ্রিক",               az: "ümumi",            hi: "कुल",          ky: "жалпы",         tg: "умумӣ",          uz: "umumiy" },
  examReadingD:  { en: "Read short texts, notices, forms.", bn: "ছোট টেক্সট, বিজ্ঞপ্তি, ফর্ম পড়ে বুঝতে পারা।", az: "Qısa mətnlər, bildirişlər, formalar oxuyub anlamaq.", hi: "छोटे पाठ, सूचनाएँ, फ़ॉर्म पढ़ें।", ky: "Кыска тексттерди, билдирүүлөрдү, формаларды окуу.", tg: "Хондани матнҳои кӯтоҳ, эълонҳо, шаклҳо.", uz: "Qisqa matnlar, eʼlonlar, shakllarni oʻqish." },
  examWritingD:  { en: "Fill forms and write 50–80 word messages.", bn: "ফর্ম পূরণ ও ৫০-৮০ শব্দের বার্তা লেখা।", az: "Forma doldurmaq və 50–80 sözlük mesaj yazmaq.", hi: "फ़ॉर्म भरना और 50–80 शब्दों के संदेश लिखना।", ky: "Форма толтуруу жана 50–80 сөздүк билдирүү жазуу.", tg: "Пур кардани шакл ва навиштани паёми 50–80 калима.", uz: "Shakllarni toʻldirish va 50–80 soʻzlik xabar yozish." },
  examListenD:   { en: "Answer questions about dialogues and announcements.", bn: "সংলাপ ও ঘোষণা শুনে প্রশ্নের উত্তর দেওয়া।", az: "Dialoq və elanları dinləyərək suallara cavab vermək.", hi: "संवाद और घोषणाओं के बारे में प्रश्नों के उत्तर दें।", ky: "Диалогдорго жана жарыяларга байланыштуу суроолорго жооп берүү.", tg: "Ҷавоб додан ба саволҳо дар бораи муколамаҳо ва эълонҳо.", uz: "Dialog va eʼlonlar haqida savollarga javob berish." },
  examSpeakD:    { en: "Oral interview with the examiner.", bn: "পরীক্ষকের সাথে মৌখিক সাক্ষাৎকার।", az: "İmtahançı ilə şifahi müsahibə.", hi: "परीक्षक के साथ मौखिक साक्षात्कार।", ky: "Сынак алуучу менен оозеки маек.", tg: "Мусоҳибаи шифоҳӣ бо имтиҳонгиранда.", uz: "Imtihon oluvchi bilan ogʻzaki suhbat." },
  startExamPrep: { en: "Start exam preparation",           bn: "পরীক্ষার প্রস্তুতি শুরু করুন", az: "İmtahan hazırlığına başla", hi: "परीक्षा की तैयारी शुरू करें", ky: "Сынак даярдыгын баштоо", tg: "Омодагии имтиҳонро оғоз кунед", uz: "Imtihon tayyorgarligini boshlash" },
  testimonials:  { en: "What our community says",          bn: "কমিউনিটির মতামত",       az: "İcmamızın rəyləri", hi: "समुदाय की राय",  ky: "Коомдун пикири", tg: "Назари ҷомеа",  uz: "Hamjamiyat fikri" },
  ctaTitle:      { en: "Start today — completely free",    bn: "আজই শুরু করুন — বিনামূল্যে", az: "Bu gün başlayın — tamamilə pulsuz", hi: "आज ही शुरू करें — पूरी तरह मुफ़्त", ky: "Бүгүн баштаңыз — толугу менен акысыз", tg: "Имрӯз оғоз кунед — комилан ройгон", uz: "Bugun boshlang — butunlay bepul" },
  ctaSub:        { en: "Start learning Lithuanian today — it's completely free", bn: "আজই লিথুয়ানিয়ান শেখা শুরু করুন — সম্পূর্ণ বিনামূল্যে", az: "Bu gün Litva dilini öyrənməyə başlayın — tamamilə pulsuzdur", hi: "आज ही लिथुआनियाई सीखना शुरू करें — यह पूरी तरह मुफ़्त है", ky: "Бүгүн литва тилин үйрөнүүнү баштаңыз — толугу менен акысыз", tg: "Имрӯз омӯзиши литвагиро оғоз кунед — комилан ройгон аст", uz: "Bugun litva tilini oʻrganishni boshlang — butunlay bepul" },
  noCard:        { en: "No credit card required",          bn: "কোনো ক্রেডিট কার্ড লাগবে না", az: "Kredit kartı tələb olunmur", hi: "कोई क्रेडिट कार्ड नहीं चाहिए", ky: "Кредиттик карта талап кылынбайт", tg: "Корти кредитӣ лозим нест", uz: "Kredit karta talab qilinmaydi" },

  // ---------- Login / Register ----------
  welcomeBack:   { en: "Welcome back",            bn: "স্বাগতম",                   az: "Xoş gəlmisiniz",       hi: "वापस स्वागत है",     ky: "Кайра кош келиңиз",     tg: "Боз хуш омадед",      uz: "Yana xush kelibsiz" },
  loginSubtitle: { en: "Sign in to your account", bn: "আপনার অ্যাকাউন্টে লগইন করুন", az: "Hesabınıza daxil olun", hi: "अपने खाते में साइन इन करें", ky: "Эсебиңизге кириңиз",   tg: "Ба ҳисоби худ ворид шавед", uz: "Hisobingizga kiring" },
  email:         { en: "Email",                   bn: "ইমেইল",                     az: "E-poçt",                hi: "ईमेल",              ky: "Электрондук почта",     tg: "Почтаи электронӣ",    uz: "Elektron pochta" },
  password:      { en: "Password",                bn: "পাসওয়ার্ড",                az: "Şifrə",                 hi: "पासवर्ड",            ky: "Сырсөз",                tg: "Парол",               uz: "Parol" },
  fullName:      { en: "Full Name",               bn: "পুরো নাম",                  az: "Tam ad",                hi: "पूरा नाम",           ky: "Толук аты",             tg: "Номи пурра",          uz: "Toʻliq ism" },
  yourName:      { en: "Your name",               bn: "আপনার নাম",                 az: "Adınız",                hi: "आपका नाम",          ky: "Атыңыз",                tg: "Номи шумо",           uz: "Ismingiz" },
  minChars:      { en: "Min 8 characters",        bn: "কমপক্ষে ৮ অক্ষর",           az: "Ən az 8 simvol",        hi: "कम से कम 8 अक्षर",   ky: "Эң аз 8 белги",         tg: "Ҳадди ақал 8 аломат", uz: "Kamida 8 ta belgi" },
  or:            { en: "or",                      bn: "অথবা",                      az: "və ya",                 hi: "या",                ky: "же",                    tg: "ё",                    uz: "yoki" },
  signInGoogle:  { en: "Sign in with Google",     bn: "Google দিয়ে লগইন করুন",   az: "Google ilə daxil ol",   hi: "Google से साइन इन",  ky: "Google аркылуу кирүү", tg: "Бо Google ворид шавед", uz: "Google bilan kirish" },
  signUpGoogle:  { en: "Sign up with Google",     bn: "Google দিয়ে যোগ দিন",     az: "Google ilə qeydiyyatdan keç", hi: "Google से साइन अप", ky: "Google аркылуу катталуу", tg: "Бо Google сабти ном", uz: "Google bilan roʻyxatdan oʻtish" },
  noAccount:     { en: "No account?",             bn: "অ্যাকাউন্ট নেই?",            az: "Hesabınız yoxdur?",     hi: "खाता नहीं है?",      ky: "Эсеп жокпу?",           tg: "Ҳисоб надоред?",      uz: "Hisobingiz yoʻqmi?" },
  haveAccount:   { en: "Already have an account?", bn: "ইতিমধ্যে অ্যাকাউন্ট আছে?", az: "Artıq hesabınız var?",  hi: "पहले से खाता है?",   ky: "Эсебиңиз барбы?",       tg: "Аллакай ҳисоб доред?", uz: "Hisobingiz bormi?" },
  createAccount: { en: "Create your account",     bn: "অ্যাকাউন্ট তৈরি করুন",       az: "Hesab yaradın",         hi: "खाता बनाएँ",         ky: "Эсеп түзүү",            tg: "Ҳисоб созед",         uz: "Hisob yaratish" },
  registerSubtitle: { en: "Create your free account", bn: "বিনামূল্যে অ্যাকাউন্ট তৈরি করুন", az: "Pulsuz hesab yaradın", hi: "मुफ़्त खाता बनाएँ", ky: "Акысыз эсеп түзүү", tg: "Ҳисоби ройгон созед", uz: "Bepul hisob yaratish" },
  loginFailed:   { en: "Could not log in. Please try again.", bn: "লগইন করতে পারছি না। আবার চেষ্টা করুন।", az: "Daxil ola bilmədik. Yenidən cəhd edin.", hi: "साइन इन नहीं हो सका। फिर से कोशिश करें।", ky: "Кире алган жокпуз. Кайра аракет кылыңыз.", tg: "Ворид шуда натавонистем. Боз кӯшиш кунед.", uz: "Kira olmadik. Qayta urinib koʻring." },
  registerFailed: { en: "Registration failed. Please try again.", bn: "রেজিস্ট্রেশন করতে পারছি না। আবার চেষ্টা করুন।", az: "Qeydiyyat alınmadı. Yenidən cəhd edin.", hi: "पंजीकरण विफल। फिर कोशिश करें।", ky: "Катталуу ишке ашкан жок. Кайра аракет.", tg: "Сабти ном ноком шуд. Боз кӯшиш кунед.", uz: "Roʻyxatdan oʻtib boʻlmadi. Qayta urinib koʻring." },

  // ---------- Dashboard ----------
  wordOfDay:     { en: "Word of the Day",         bn: "আজকের শব্দ",                az: "Günün sözü",            hi: "आज का शब्द",        ky: "Күндүн сөзү",           tg: "Калимаи рӯз",         uz: "Kun soʻzi" },
  quickStart:    { en: "Quick Start",             bn: "দ্রুত শুরু করুন",            az: "Sürətli başlanğıc",     hi: "त्वरित शुरुआत",      ky: "Тез баштоо",            tg: "Оғози тез",            uz: "Tezkor boshlash" },
  continueLearn: { en: "Continue Learning",       bn: "শিক্ষা চালিয়ে যান",         az: "Öyrənməyə davam edin",  hi: "सीखना जारी रखें",    ky: "Үйрөнүүнү улантуу",     tg: "Омӯзишро идома диҳед", uz: "Oʻrganishda davom etish" },
  dailyGoal:     { en: "Daily Goal",              bn: "আজকের লক্ষ্য",               az: "Gündəlik hədəf",        hi: "दैनिक लक्ष्य",       ky: "Күнүмдүк максат",       tg: "Ҳадафи ҳаррӯза",       uz: "Kunlik maqsad" },
  dueReview:     { en: "Due for Review",          bn: "পর্যালোচনার সময়",           az: "Təkrar üçün hazır",     hi: "समीक्षा के लिए तैयार", ky: "Кайталоого даяр",       tg: "Барои такрор омода",   uz: "Takrorlash uchun tayyor" },
  reviewNow:     { en: "Review now",              bn: "এখনই পর্যালোচনা করুন",       az: "İndi təkrar et",        hi: "अभी समीक्षा करें",   ky: "Дароо кайталоо",        tg: "Ҳозир такрор кунед",   uz: "Hozir takrorlash" },
  wordsLearned:  { en: "Words Learned",           bn: "শেখা শব্দ",                  az: "Öyrənilmiş sözlər",     hi: "सीखे गए शब्द",       ky: "Үйрөнүлгөн сөздөр",     tg: "Калимаҳои омӯхташуда", uz: "Oʻrganilgan soʻzlar" },
  lessonsDone:   { en: "Lessons Done",            bn: "সম্পন্ন পাঠ",                az: "Tamamlanmış dərslər",   hi: "पूर्ण किए पाठ",      ky: "Аякталган сабактар",    tg: "Дарсҳои анҷомшуда",    uz: "Tugatilgan darslar" },
  quizAvg:       { en: "Quiz Average",            bn: "কুইজ গড়",                   az: "Test ortalaması",       hi: "क्विज़ औसत",         ky: "Тест орточосу",         tg: "Миёнаи тест",          uz: "Test oʻrtachasi" },
  daysActive:    { en: "Days Active",             bn: "সক্রিয় দিন",                az: "Aktiv günlər",          hi: "सक्रिय दिन",         ky: "Активдүү күндөр",       tg: "Рӯзҳои фаъол",         uz: "Faol kunlar" },
  wordsDueToday: { en: "words due today",         bn: "আজ পর্যালোচনার জন্য শব্দ",   az: "bu gün təkrar üçün söz", hi: "आज समीक्षा के लिए शब्द", ky: "бүгүн кайталоо үчүн сөздөр", tg: "имрӯз барои такрор калимаҳо", uz: "bugun takrorlash uchun soʻzlar" },
  earnedToday:   { en: "earned today",            bn: "আজ অর্জিত",                  az: "bu gün qazanıldı",      hi: "आज अर्जित",          ky: "бүгүн алынды",          tg: "имрӯз ба даст оварда шуд", uz: "bugun olingan" },
  reviewVocab:   { en: "Review vocabulary",       bn: "শব্দ পর্যালোচনা",            az: "Lüğəti təkrar et",      hi: "शब्दावली समीक्षा",   ky: "Сөздүктү кайталоо",     tg: "Луғатро такрор кунед", uz: "Lugʻatni takrorlash" },
  seeAllWords:   { en: "See all words",           bn: "সব শব্দ দেখুন",              az: "Bütün sözlərə bax",     hi: "सभी शब्द देखें",     ky: "Бардык сөздөрдү көрүү", tg: "Ҳамаи калимаҳоро бинед", uz: "Barcha soʻzlarni koʻrish" },
  alphabetNumbers: { en: "Alphabet & numbers",    bn: "বর্ণমালা ও সংখ্যা",          az: "Əlifba və rəqəmlər",    hi: "वर्णमाला और संख्याएँ", ky: "Алфавит жана сандар",   tg: "Алифбо ва рақамҳо",    uz: "Alifbo va raqamlar" },
  learnGrammar:  { en: "Learn grammar",           bn: "ব্যাকরণ শিখুন",              az: "Qrammatika öyrən",      hi: "व्याकरण सीखें",      ky: "Грамматика үйрөнүү",    tg: "Грамматикаро омӯзед",  uz: "Grammatika oʻrganish" },
  realDialogues: { en: "Real-life dialogues",     bn: "বাস্তব সংলাপ",               az: "Real həyat dialoqları", hi: "वास्तविक संवाद",     ky: "Реалдуу диалогдор",     tg: "Муколамаҳои воқеӣ",    uz: "Hayotiy dialoglar" },
  readingPractice: { en: "Reading practice",      bn: "পাঠ বোঝার অনুশীলন",          az: "Oxu təcrübəsi",         hi: "पठन अभ्यास",         ky: "Окуу машыгуусу",        tg: "Машқи хониш",          uz: "Oʻqish mashqi" },
  testKnowledge: { en: "Test your knowledge",     bn: "জ্ঞান যাচাই করুন",           az: "Biliyinizi yoxlayın",   hi: "अपना ज्ञान परखें",   ky: "Билимиңизди сынаңыз",   tg: "Дониши худро санҷед",  uz: "Bilimingizni sinab koʻring" },
  a1ExamPrepShort: { en: "A1 exam preparation",   bn: "A1 পরীক্ষার প্রস্তুতি",      az: "A1 imtahan hazırlığı",  hi: "A1 परीक्षा की तैयारी", ky: "A1 сынак даярдыгы",     tg: "Омодагии имтиҳони A1", uz: "A1 imtihon tayyorgarligi" },
  greetingMorning: { en: "Good morning",          bn: "সুপ্রভাত",                   az: "Sabahınız xeyir",       hi: "सुप्रभात",           ky: "Кутмандуу таң",         tg: "Субҳ ба хайр",         uz: "Hayrli tong" },
  greetingAfternoon: { en: "Good afternoon",      bn: "শুভ বিকেল",                  az: "Günortanız xeyir",      hi: "नमस्ते",            ky: "Кутмандуу күн",         tg: "Нимаи рӯз ба хайр",    uz: "Hayrli kun" },
  greetingEvening: { en: "Good evening",          bn: "শুভ সন্ধ্যা",                az: "Axşamınız xeyir",       hi: "शुभ संध्या",         ky: "Кутмандуу кеч",         tg: "Шом ба хайр",          uz: "Hayrli oqshom" },

  // ---------- Lessons / Vocabulary / Flashcards / Exam common ----------
  lessonsTitle:  { en: "Lessons",                 bn: "পাঠসমূহ",                    az: "Dərslər",               hi: "पाठ",               ky: "Сабактар",              tg: "Дарсҳо",               uz: "Darslar" },
  lessonsSub:    { en: "Structured A1 curriculum", bn: "গঠনমূলক A1 পাঠ্যক্রম",     az: "Strukturlaşdırılmış A1 kurikulumu", hi: "संरचित A1 पाठ्यक्रम", ky: "Структуралык A1 куррикулум", tg: "Барномаи дарсии сохтории A1", uz: "Tuzilgan A1 oʻquv dasturi" },
  vocabTitle:    { en: "Vocabulary",              bn: "শব্দ ভাণ্ডার",                az: "Lüğət",                 hi: "शब्दावली",          ky: "Сөздүк",                tg: "Луғат",                uz: "Lugʻat" },
  vocabSub:      { en: "All A1 words with audio and translation", bn: "A1 স্তরের সব শব্দ অডিও ও অনুবাদসহ", az: "Səs və tərcümə ilə bütün A1 sözləri", hi: "ऑडियो और अनुवाद के साथ सभी A1 शब्द", ky: "Үн жана котормо менен бардык A1 сөздөрү", tg: "Ҳамаи калимаҳои A1 бо аудио ва тарҷума", uz: "Audio va tarjima bilan barcha A1 soʻzlari" },
  flashTitle:    { en: "Flashcards",              bn: "ফ্ল্যাশকার্ড",                az: "Flaşkartlar",          hi: "फ्लैशकार्ड",         ky: "Карточкалар",           tg: "Кортҳои хотиравӣ",     uz: "Flashkartalar" },
  flashSub:      { en: "Smart spaced repetition for vocabulary", bn: "শব্দের জন্য স্মার্ট স্পেসড রিপিটিশন", az: "Lüğət üçün ağıllı aralıqlı təkrar", hi: "शब्दावली के लिए स्मार्ट स्पेस्ड रिपीटिशन", ky: "Сөздүк үчүн акылдуу аралыктуу кайталоо", tg: "Такрори ҳушмандонаи фосиладор барои луғат", uz: "Lugʻat uchun aqlli oraliqli takrorlash" },
  examTitleFull: { en: "A1 Exam Preparation",     bn: "A1 পরীক্ষার প্রস্তুতি",      az: "A1 İmtahan Hazırlığı",  hi: "A1 परीक्षा की तैयारी", ky: "A1 Сынак Даярдыгы",     tg: "Омодагии Имтиҳони A1", uz: "A1 Imtihon Tayyorgarligi" },
  examSubLong:   { en: "Complete preparation for the A1 Lithuanian language exam", bn: "A1 লিথুয়ানিয়ান ভাষা পরীক্ষার সম্পূর্ণ প্রস্তুতি", az: "A1 Litva dili imtahanı üçün tam hazırlıq", hi: "A1 लिथुआनियाई भाषा परीक्षा की पूर्ण तैयारी", ky: "A1 Литва тил сынагына толук даярдык", tg: "Омодагии пурра барои имтиҳони забони литвагии A1", uz: "A1 Litva tili imtihoniga toʻliq tayyorgarlik" },
  startSection:  { en: "Start section",           bn: "অংশ শুরু করুন",              az: "Bölməyə başla",         hi: "अनुभाग शुरू करें",   ky: "Бөлүмдү баштоо",        tg: "Бахшро оғоз кунед",    uz: "Boʻlimni boshlash" },
  mockExam:      { en: "Mock Exam",               bn: "মক পরীক্ষা",                 az: "Sınaq imtahanı",        hi: "मॉक परीक्षा",        ky: "Мок сынак",             tg: "Имтиҳони омӯзишӣ",     uz: "Sinov imtihoni" },
  takeMock:      { en: "Take a full mock exam",   bn: "একটি পূর্ণাঙ্গ মক পরীক্ষা দিন", az: "Tam sınaq imtahanı verin", hi: "पूर्ण मॉक परीक्षा दें", ky: "Толук мок сынак тапшырыңыз", tg: "Имтиҳони пурраи омӯзишӣ диҳед", uz: "Toʻliq sinov imtihonini topshiring" },

  // ---------- Misc lesson / quiz / progress ----------
  level:         { en: "Level",                   bn: "স্তর",                       az: "Səviyyə",               hi: "स्तर",              ky: "Деңгээл",               tg: "Сатҳ",                 uz: "Daraja" },
  topic:         { en: "Topic",                   bn: "বিষয়",                      az: "Mövzu",                 hi: "विषय",              ky: "Тема",                  tg: "Мавзӯъ",               uz: "Mavzu" },
  all:           { en: "All",                     bn: "সব",                         az: "Hamısı",                hi: "सभी",               ky: "Бардыгы",               tg: "Ҳама",                 uz: "Hammasi" },
  beginner:      { en: "Beginner",                bn: "শিক্ষানবিশ",                 az: "Başlanğıc",             hi: "शुरुआती",            ky: "Башталгыч",             tg: "Сатҳи ибтидоӣ",        uz: "Boshlangʻich" },
  progress:      { en: "Progress",                bn: "অগ্রগতি",                    az: "İrəliləyiş",            hi: "प्रगति",            ky: "Прогресс",              tg: "Пешрафт",              uz: "Taraqqiyot" },
  startLesson:   { en: "Start lesson",            bn: "পাঠ শুরু করুন",              az: "Dərsə başla",           hi: "पाठ शुरू करें",      ky: "Сабакты баштоо",        tg: "Дарсро оғоз кунед",    uz: "Darsni boshlash" },
  lessonComplete: { en: "Lesson complete",        bn: "পাঠ সম্পন্ন",                az: "Dərs tamamlandı",       hi: "पाठ पूर्ण",         ky: "Сабак аякталды",        tg: "Дарс анҷом шуд",       uz: "Dars tugatildi" },
  myProgress:    { en: "My Progress",             bn: "আমার অগ্রগতি",               az: "Mənim irəliləyişim",    hi: "मेरी प्रगति",        ky: "Менин прогрессим",      tg: "Пешрафти ман",         uz: "Mening taraqqiyotim" },
  account:       { en: "Account",                 bn: "অ্যাকাউন্ট",                 az: "Hesab",                 hi: "खाता",              ky: "Эсеп",                  tg: "Ҳисоб",                uz: "Hisob" },
  settings:      { en: "Settings",                bn: "সেটিংস",                    az: "Parametrlər",           hi: "सेटिंग्स",          ky: "Жөндөөлөр",             tg: "Танзимот",             uz: "Sozlamalar" },
  preferredLang: { en: "Preferred Language",      bn: "পছন্দের ভাষা",               az: "Tərcih edilən dil",     hi: "पसंदीदा भाषा",       ky: "Тандалган тил",         tg: "Забони интихобшуда",   uz: "Tanlangan til" },
  filterBy:      { en: "Filter by",               bn: "ফিল্টার",                    az: "Filtr",                 hi: "फ़िल्टर",           ky: "Чыпка",                 tg: "Филтр",                uz: "Filtr" },
  totalWords:    { en: "Total words",             bn: "মোট শব্দ",                   az: "Cəmi söz",              hi: "कुल शब्द",          ky: "Жалпы сөздөр",          tg: "Ҳамагӣ калимаҳо",      uz: "Jami soʻzlar" },
  sectionLT:     { en: "Lithuanian",              bn: "লিথুয়ানিয়ান",                az: "Litva dili",            hi: "लिथुआनियाई",         ky: "Литва тили",            tg: "Литвагӣ",              uz: "Litva tili" },
  sectionEN:     { en: "English",                 bn: "ইংরেজি",                    az: "İngilis",               hi: "अंग्रेज़ी",          ky: "Англис",                tg: "Англисӣ",              uz: "Ingliz" },
  yourLanguage:  { en: "Your language",           bn: "আপনার ভাষা",                az: "Sizin diliniz",         hi: "आपकी भाषा",         ky: "Сиздин тилиңиз",        tg: "Забони шумо",          uz: "Sizning tilingiz" },

  // ---------- Footer ----------
  about:         { en: "About",                    bn: "আমাদের সম্পর্কে",            az: "Haqqımızda",            hi: "हमारे बारे में",      ky: "Биз жөнүндө",           tg: "Дар бораи мо",         uz: "Biz haqimizda" },
  privacy:       { en: "Privacy",                  bn: "গোপনীয়তা",                  az: "Məxfilik",              hi: "गोपनीयता",           ky: "Купуялык",              tg: "Махфият",              uz: "Maxfiylik" },
  contact:       { en: "Contact",                  bn: "যোগাযোগ",                    az: "Əlaqə",                 hi: "संपर्क",            ky: "Байланыш",              tg: "Тамос",                uz: "Bogʻlanish" },
  footerTagline: { en: "Made with ❤️ for international learners of Lithuanian", bn: "❤️ দিয়ে তৈরি — লিথুয়ানিয়ান শেখার আন্তর্জাতিক শিক্ষার্থীদের জন্য", az: "❤️ ilə Litva dilini öyrənən beynəlxalq tələbələr üçün hazırlanmışdır", hi: "❤️ के साथ अंतरराष्ट्रीय लिथुआनियाई शिक्षार्थियों के लिए बनाया गया", ky: "❤️ менен литва тилин үйрөнгөн эл аралык окуучулар үчүн жасалган", tg: "Бо ❤️ барои донишҷӯёни байналмилалии забони литвагӣ сохта шудааст", uz: "❤️ bilan Litva tilini oʻrganadigan xalqaro talabalar uchun yaratilgan" },
  developedBy:   { en: "Developed by",             bn: "ডেভেলপ করেছেন",              az: "Hazırlayan",            hi: "विकसित किया",        ky: "Иштеп чыккан",          tg: "Тарроҳ",               uz: "Ishlab chiqaruvchi" },

  // ---------- Vocabulary / Flashcards page extras ----------
  searchVocab:   { en: "Search vocabulary...",     bn: "শব্দ খুঁজুন...",              az: "Lüğətdə axtar...",      hi: "शब्दावली खोजें...",  ky: "Сөздүктөн издөө...",     tg: "Дар луғат ҷустуҷӯ...", uz: "Lugʻatda qidirish..." },
  filters:       { en: "Filters",                  bn: "ফিল্টার",                    az: "Filtrlər",              hi: "फ़िल्टर",            ky: "Чыпкалар",              tg: "Филтрҳо",              uz: "Filtrlar" },
  reset:         { en: "Reset",                    bn: "রিসেট",                       az: "Sıfırla",               hi: "रीसेट",             ky: "Баштапкы абалга",       tg: "Бозсозӣ",              uz: "Tiklash" },
  showing:       { en: "Showing",                  bn: "দেখানো হচ্ছে",                az: "Göstərilir",            hi: "दिखाया जा रहा",      ky: "Көрсөтүлдү",             tg: "Намоиш дода мешавад",  uz: "Koʻrsatilmoqda" },
  of:            { en: "of",                       bn: "এর মধ্যে",                    az: "/",                     hi: "में से",            ky: "ичинен",                tg: "аз",                   uz: "dan" },
  partOfSpeech:  { en: "Part of speech",           bn: "শব্দ-শ্রেণী",                 az: "Nitq hissəsi",          hi: "शब्द भेद",           ky: "Сөз түркүмү",           tg: "Ҳиссаи нутқ",          uz: "Soʻz turkumi" },
  gender:        { en: "Gender",                   bn: "লিঙ্গ",                       az: "Cins",                  hi: "लिंग",              ky: "Жыныш",                 tg: "Ҷинс",                 uz: "Jins" },
  newCard:       { en: "New",                      bn: "নতুন",                        az: "Yeni",                  hi: "नया",               ky: "Жаңы",                  tg: "Нав",                  uz: "Yangi" },
  learning:      { en: "Learning",                 bn: "শিখছেন",                     az: "Öyrənilir",             hi: "सीख रहे",            ky: "Үйрөнүүдө",             tg: "Дар ҳоли омӯзиш",      uz: "Oʻrganilmoqda" },
  mastered:      { en: "Mastered",                 bn: "আয়ত্ত",                      az: "Mənimsənilib",          hi: "पारंगत",            ky: "Толук үйрөнүлгөн",      tg: "Аз худ карда шуд",     uz: "Oʻzlashtirildi" },
  flipCard:      { en: "Flip card",                bn: "কার্ড উল্টান",                az: "Kartı çevirin",         hi: "कार्ड पलटें",        ky: "Карточканы оодаруу",    tg: "Кортро баргардонед",   uz: "Kartani aylantiring" },
  iKnewIt:       { en: "I knew it",                bn: "জানতাম",                     az: "Bilirdim",              hi: "मुझे पता था",        ky: "Билчүмүн",              tg: "Медонистам",            uz: "Bilardim" },
  difficult:     { en: "Difficult",                bn: "কঠিন",                        az: "Çətin",                 hi: "कठिन",              ky: "Кыйын",                 tg: "Душвор",                uz: "Qiyin" },
  good:          { en: "Good",                     bn: "ভালো",                        az: "Yaxşı",                 hi: "अच्छा",             ky: "Жакшы",                 tg: "Хуб",                   uz: "Yaxshi" },
  easy:          { en: "Easy",                     bn: "সহজ",                         az: "Asan",                  hi: "आसान",              ky: "Оңой",                  tg: "Осон",                  uz: "Oson" },
  example:       { en: "Example",                  bn: "উদাহরণ",                     az: "Nümunə",                hi: "उदाहरण",             ky: "Мисал",                 tg: "Мисол",                 uz: "Misol" },
  meaning:       { en: "Meaning",                  bn: "অর্থ",                        az: "Mənası",                hi: "अर्थ",              ky: "Мааниси",               tg: "Маънӣ",                 uz: "Maʼnosi" },
  translation:   { en: "Translation",              bn: "অনুবাদ",                     az: "Tərcümə",               hi: "अनुवाद",             ky: "Котормо",               tg: "Тарҷума",               uz: "Tarjima" },

  // ---------- Profile ----------
  myProfile:     { en: "My Profile",               bn: "আমার প্রোফাইল",              az: "Mənim Profilim",        hi: "मेरी प्रोफ़ाइल",      ky: "Менин профилим",        tg: "Профили ман",          uz: "Mening profilim" },
  editProfile:   { en: "Edit profile",             bn: "প্রোফাইল সম্পাদনা",           az: "Profili redaktə et",    hi: "प्रोफ़ाइल संपादित करें", ky: "Профилди оңдоо",        tg: "Профилро таҳрир кунед", uz: "Profilni tahrirlash" },
  achievements:  { en: "Achievements",             bn: "অর্জন",                       az: "Nailiyyətlər",          hi: "उपलब्धियाँ",         ky: "Жетишкендиктер",        tg: "Дастовардҳо",          uz: "Yutuqlar" },
  totalXP:       { en: "Total XP",                 bn: "মোট XP",                      az: "Ümumi XP",              hi: "कुल XP",            ky: "Жалпы XP",              tg: "XP-и умумӣ",            uz: "Jami XP" },
  streak:        { en: "Streak",                   bn: "স্ট্রিক",                    az: "Silsilə",               hi: "स्ट्रीक",            ky: "Катар",                 tg: "Силсила",               uz: "Ketma-ketlik" },
  days:          { en: "days",                     bn: "দিন",                         az: "gün",                   hi: "दिन",               ky: "күн",                   tg: "рӯз",                   uz: "kun" },
  joinedOn:      { en: "Joined on",                bn: "যোগ দিয়েছেন",                az: "Qoşulub",               hi: "शामिल हुए",          ky: "Кошулган",              tg: "Ҳамроҳ шудааст",       uz: "Qoʻshilgan" },
  signOutConfirm:{ en: "Sign out of your account?", bn: "অ্যাকাউন্ট থেকে সাইন আউট করবেন?", az: "Hesabdan çıxmaq istəyirsiniz?", hi: "क्या आप साइन आउट करना चाहते हैं?", ky: "Эсептен чыгасызбы?", tg: "Аз ҳисоб баромадан мехоҳед?", uz: "Hisobdan chiqmoqchimisiz?" },

  // ---------- Quizzes ----------
  quizzesTitle:  { en: "Quizzes",                  bn: "কুইজ",                       az: "Testlər",               hi: "क्विज़",            ky: "Тесттер",                tg: "Тестҳо",               uz: "Testlar" },
  quizzesSub:    { en: "Test your knowledge",      bn: "জ্ঞান যাচাই করুন",           az: "Biliyinizi yoxlayın",   hi: "अपना ज्ञान परखें",   ky: "Билимиңизди сынаңыз",   tg: "Дониши худро санҷед",  uz: "Bilimingizni sinab koʻring" },
  startQuiz:     { en: "Start quiz",               bn: "কুইজ শুরু",                  az: "Testə başla",           hi: "क्विज़ शुरू करें",   ky: "Тестти баштоо",         tg: "Тестро оғоз кунед",    uz: "Testni boshlash" },
  questions:     { en: "questions",                bn: "প্রশ্ন",                     az: "sual",                  hi: "प्रश्न",            ky: "суроо",                 tg: "савол",                uz: "savol" },
  yourScore:     { en: "Your score",               bn: "আপনার স্কোর",                az: "Sizin nəticəniz",        hi: "आपका स्कोर",         ky: "Сиздин упайыңыз",       tg: "Натиҷаи шумо",         uz: "Sizning natijangiz" },
  correct:       { en: "Correct",                  bn: "সঠিক",                       az: "Düzgün",                hi: "सही",                ky: "Туура",                 tg: "Дуруст",               uz: "Toʻgʻri" },
  incorrect:     { en: "Incorrect",                bn: "ভুল",                        az: "Səhv",                  hi: "गलत",                ky: "Туура эмес",            tg: "Нодуруст",             uz: "Notoʻgʻri" },
  finishQuiz:    { en: "Finish quiz",              bn: "কুইজ শেষ করুন",              az: "Testi bitir",           hi: "क्विज़ समाप्त करें", ky: "Тестти бүтүрүү",        tg: "Тестро ба итмом расонед", uz: "Testni tugatish" },
  tryAgain:      { en: "Try again",                bn: "আবার চেষ্টা",                az: "Yenidən cəhd et",       hi: "फिर कोशिश करें",     ky: "Кайра аракет",          tg: "Боз кӯшиш кунед",      uz: "Qayta urinish" },

  // ---------- Search ----------
  searchPlaceholder: { en: "Search vocabulary & lessons...", bn: "শব্দ ও পাঠ খুঁজুন...",        az: "Lüğət və dərslərdə axtar...", hi: "शब्दावली और पाठ खोजें...", ky: "Сөздүк жана сабактардан издөө...", tg: "Дар луғат ва дарсҳо ҷустуҷӯ...", uz: "Lugʻat va darslarda qidirish..." },
  recent:        { en: "Recent",                   bn: "সাম্প্রতিক",                  az: "Son",                   hi: "हाल का",            ky: "Акыркы",                 tg: "Охирин",                uz: "Soʻnggi" },
  navigate:      { en: "navigate",                 bn: "নেভিগেট",                     az: "naviqasiya",            hi: "नेविगेट",            ky: "өтүү",                   tg: "ҳаракат",               uz: "harakat" },
  select:        { en: "select",                   bn: "নির্বাচন",                    az: "seç",                   hi: "चुनें",              ky: "тандоо",                 tg: "интихоб",               uz: "tanlash" },
  close:         { en: "close",                    bn: "বন্ধ",                        az: "bağla",                 hi: "बंद करें",           ky: "жабуу",                  tg: "пӯшидан",               uz: "yopish" },

  // ---------- Flashcards page ----------
  studyMode:     { en: "Study Mode",                bn: "অধ্যয়ন মোড",                az: "Təlim rejimi",          hi: "अध्ययन मोड",        ky: "Окуу режими",            tg: "Реҷаи омӯзиш",          uz: "Oʻqish rejimi" },
  reviewMode:    { en: "Review Mode",               bn: "পর্যালোচনা মোড",            az: "Təkrar rejimi",         hi: "समीक्षा मोड",        ky: "Кайталоо режими",        tg: "Реҷаи такрор",          uz: "Takrorlash rejimi" },
  decks:         { en: "Decks",                     bn: "ডেক",                        az: "Dəstələr",              hi: "डेक",               ky: "Карточкалар жыйнагы",   tg: "Дастаҳо",               uz: "Toʻplamlar" },
  myDecks:       { en: "My Decks",                  bn: "আমার ডেক",                   az: "Mənim dəstələrim",      hi: "मेरे डेक",           ky: "Менин жыйнактарым",     tg: "Дастаҳои ман",          uz: "Mening toʻplamlarim" },
  cardsToReview: { en: "cards to review",           bn: "পর্যালোচনার জন্য কার্ড",      az: "təkrar üçün kartlar",   hi: "समीक्षा के लिए कार्ड", ky: "кайталоо үчүн карточкалар", tg: "кортҳо барои такрор", uz: "takrorlash uchun kartalar" },
  showAnswer:    { en: "Show Answer",               bn: "উত্তর দেখান",                 az: "Cavabı göstər",         hi: "उत्तर दिखाएँ",      ky: "Жоопту көрсөтүү",        tg: "Ҷавобро нишон диҳед",   uz: "Javobni koʻrsatish" },
  hideAnswer:    { en: "Hide Answer",               bn: "উত্তর লুকান",                 az: "Cavabı gizlət",         hi: "उत्तर छुपाएँ",       ky: "Жоопту жашыруу",         tg: "Ҷавобро пинҳон кунед",  uz: "Javobni yashirish" },
  cardOf:        { en: "of",                        bn: "এর মধ্যে",                    az: "/",                     hi: "में से",            ky: "ичинен",                 tg: "аз",                    uz: "dan" },

  // ---------- Homepage v2 ----------
  freeForever:   { en: "Free",                                      bn: "বিনামূল্যে",                 az: "Pulsuz",                    hi: "मुफ़्त",                       ky: "Акысыз",                          tg: "Ройгон",                    uz: "Bepul" },
  trustedBy:     { en: "Trusted by learners from 9 countries",      bn: "৯টি দেশের শিক্ষার্থীদের আস্থা", az: "9 ölkədən tələbələrin etibar etdiyi", hi: "9 देशों के शिक्षार्थियों का भरोसा", ky: "9 өлкөдөн окуучулар ишенген", tg: "Эътимоди донишҷӯён аз 9 кишвар", uz: "9 mamlakat talabalari ishonadi" },
  statLearners:  { en: "Active learners",                            bn: "সক্রিয় শিক্ষার্থী",         az: "Aktiv tələbələr",           hi: "सक्रिय शिक्षार्थी",          ky: "Активдүү окуучулар",            tg: "Донишҷӯёни фаъол",          uz: "Faol talabalar" },
  statWords:     { en: "A1 vocabulary words",                        bn: "A1 শব্দ ভাণ্ডার",            az: "A1 lüğət sözləri",          hi: "A1 शब्दावली शब्द",          ky: "A1 сөздөрү",                    tg: "Калимаҳои A1",              uz: "A1 lugʻat soʻzlari" },
  statLessons:   { en: "Structured lessons",                          bn: "গঠনমূলক পাঠ",                az: "Strukturlaşdırılmış dərslər", hi: "संरचित पाठ",                ky: "Структуралык сабактар",         tg: "Дарсҳои сохторшуда",        uz: "Tuzilgan darslar" },
  statLanguages: { en: "Native languages",                            bn: "মাতৃভাষা",                   az: "Ana dillər",                hi: "मातृभाषाएँ",                ky: "Эне тилдер",                    tg: "Забонҳои модарӣ",            uz: "Ona tillari" },
  howItWorks:    { en: "How it works",                                bn: "এটি কীভাবে কাজ করে",         az: "Necə işləyir",              hi: "यह कैसे काम करता है",      ky: "Кантип иштейт",                  tg: "Чӣ тавр кор мекунад",       uz: "Qanday ishlaydi" },
  step1Title:    { en: "Pick your language",                          bn: "আপনার ভাষা বাছুন",          az: "Dilinizi seçin",            hi: "अपनी भाषा चुनें",           ky: "Тилиңизди тандаңыз",            tg: "Забони худро интихоб кунед", uz: "Tilingizni tanlang" },
  step1Desc:     { en: "Set the interface to one of 7 native languages.", bn: "৭টি মাতৃভাষার একটি বেছে নিন।", az: "İnterfeysi 7 ana dildən birinə qurun.", hi: "इंटरफ़ेस को 7 मातृभाषाओं में से एक पर सेट करें।", ky: "Интерфейсти 7 эне тилдин бирине коюңуз.", tg: "Интерфейсро ба яке аз 7 забони модарӣ танзим кунед.", uz: "Interfeysni 7 ona tilidan biriga sozlang." },
  step2Title:    { en: "Learn with audio",                            bn: "অডিও দিয়ে শিখুন",            az: "Səslə öyrənin",             hi: "ऑडियो के साथ सीखें",       ky: "Үн менен үйрөнүңүз",             tg: "Бо аудио омӯзед",           uz: "Audio bilan oʻrganing" },
  step2Desc:     { en: "Hear native Lithuanian on every word and example.", bn: "প্রতিটি শব্দ ও উদাহরণে স্থানীয় উচ্চারণ শুনুন।", az: "Hər söz və nümunədə doğma Litva səsi.", hi: "हर शब्द और उदाहरण पर मूल लिथुआनियाई।", ky: "Ар бир сөз жана мисалда жергиликтүү литва тили.", tg: "Литвагии аслӣ дар ҳар калима ва мисол.", uz: "Har bir soʻz va misolda asl litva." },
  step3Title:    { en: "Pass the A1 exam",                             bn: "A1 পরীক্ষা পাস করুন",        az: "A1 imtahanını keçin",       hi: "A1 परीक्षा पास करें",       ky: "A1 сынактан өтүңүз",             tg: "Имтиҳони A1-ро супоред",     uz: "A1 imtihondan oʻting" },
  step3Desc:     { en: "Practice every section: listening, reading, writing, speaking.", bn: "প্রতিটি অংশ অনুশীলন করুন: শোনা, পড়া, লেখা, বলা।", az: "Hər bölməni məşq edin: dinləmə, oxu, yazı, danışıq.", hi: "हर अनुभाग का अभ्यास करें: श्रवण, पठन, लेखन, बोलना।", ky: "Ар бир бөлүмдү машыктырыңыз: угуу, окуу, жазуу, сүйлөө.", tg: "Ҳар бахшро машқ кунед: гӯш кардан, хониш, навиштан, гуфтор.", uz: "Har bir boʻlimni mashq qiling: tinglash, oʻqish, yozish, soʻzlash." },

  // Coffee / support section
  supportTitle:  { en: "Like KalbaLab? Buy us a coffee ☕",            bn: "KalbaLab ভালো লাগলো? এক কাপ কফি কিনে দিন ☕", az: "KalbaLab xoşunuza gəldi? Bizə qəhvə alın ☕", hi: "KalbaLab पसंद आया? हमें एक कॉफ़ी पिलाएँ ☕", ky: "KalbaLab жактыбы? Бизге кофе сатып бериңиз ☕", tg: "KalbaLab маъқул шуд? Барои мо қаҳва харед ☕", uz: "KalbaLab yoqdimi? Bizga qahva olib bering ☕" },
  supportDesc:   { en: "KalbaLab is free to use. If it helped you on your Lithuanian journey, a small tip keeps the servers running and the lessons growing.", bn: "KalbaLab বিনামূল্যে ব্যবহার করা যায়। যদি এটি আপনার লিথুয়ানিয়ান যাত্রায় সাহায্য করে থাকে, একটি ছোট অনুদান সার্ভার চালু রাখতে সাহায্য করবে।", az: "KalbaLab istifadə üçün pulsuzdur. Litva səyahətinizə kömək etdisə, kiçik bir bağış serverləri işlək saxlamağa kömək edir.", hi: "KalbaLab उपयोग के लिए मुफ़्त है। यदि इसने आपकी लिथुआनियाई यात्रा में मदद की हो, एक छोटा सा योगदान सर्वर चलते रखता है।", ky: "KalbaLab колдонуу үчүн акысыз. Эгерде ал сизге литва жолуңузда жардам берсе, бир аз жардам серверди иштеп кармайт.", tg: "KalbaLab барои истифода ройгон аст. Агар он ба сафари литвагии шумо кӯмак карда бошад, кӯмаки хурд серверҳоро фаъол нигоҳ медорад.", uz: "KalbaLab foydalanish uchun bepul. Agar u sizning litva sayohatingizda yordam bergan boʻlsa, kichik xayriya serverlarni ishlab turishda yordam beradi." },
  buyCoffee:     { en: "Buy me a coffee",                              bn: "কফি কিনে দিন",                az: "Mənə qəhvə al",             hi: "मुझे कॉफ़ी पिलाओ",         ky: "Маа кофе сатып бериңиз",        tg: "Барои ман қаҳва харед",      uz: "Menga qahva olib bering" },

  // Footer v2
  product:       { en: "Product",       bn: "পণ্য",            az: "Məhsul",      hi: "उत्पाद",     ky: "Продукт",       tg: "Маҳсулот",      uz: "Mahsulot" },
  resources:     { en: "Resources",     bn: "সম্পদ",           az: "Resurslar",   hi: "संसाधन",     ky: "Ресурстар",     tg: "Захираҳо",       uz: "Resurslar" },
  community:     { en: "Community",     bn: "কমিউনিটি",       az: "İcma",        hi: "समुदाय",     ky: "Жамаат",        tg: "Ҷомеа",          uz: "Hamjamiyat" },
  legal:         { en: "Legal",         bn: "আইনি",            az: "Hüquqi",      hi: "कानूनी",    ky: "Юридикалык",    tg: "Ҳуқуқӣ",         uz: "Huquqiy" },
  terms:         { en: "Terms",         bn: "শর্তাবলী",         az: "Şərtlər",     hi: "शर्तें",     ky: "Шарттар",       tg: "Шартҳо",         uz: "Shartlar" },
  cookies:       { en: "Cookies",       bn: "কুকিজ",            az: "Kukilər",     hi: "कुकीज़",    ky: "Кукилер",       tg: "Кукиҳо",         uz: "Cookie-fayllar" },
  faq:           { en: "FAQ",           bn: "সচরাচর জিজ্ঞাসা", az: "Tez-tez verilən suallar", hi: "अक्सर पूछे जाने वाले प्रश्न", ky: "Көп берилген суроолор", tg: "Саволҳои зуд-зуд",   uz: "Tez-tez beriladigan savollar" },
  blog:          { en: "Blog",          bn: "ব্লগ",             az: "Bloq",        hi: "ब्लॉग",     ky: "Блог",          tg: "Блог",           uz: "Blog" },
  examInfo:      { en: "A1 Exam Info",  bn: "A1 পরীক্ষার তথ্য", az: "A1 imtahan məlumatı", hi: "A1 परीक्षा जानकारी", ky: "A1 сынак тууралуу", tg: "Маълумот дар бораи имтиҳони A1", uz: "A1 imtihon haqida" },
  followUs:      { en: "Follow us",     bn: "আমাদের অনুসরণ করুন", az: "Bizi izləyin", hi: "हमें फ़ॉलो करें", ky: "Бизди ээрчиңиз", tg: "Моро пайравӣ кунед", uz: "Bizni kuzating" },
  newsletter:    { en: "Get learning tips",  bn: "শেখার টিপস পান", az: "Öyrənmə məsləhətləri", hi: "सीखने के टिप्स पाएँ", ky: "Үйрөнүү кеңештерин алыңыз", tg: "Маслиҳатҳои омӯзишро гиред", uz: "Oʻqish maslahatlarini oling" },
  yourEmail:     { en: "your@email.com", bn: "your@email.com",  az: "your@email.com", hi: "your@email.com", ky: "your@email.com", tg: "your@email.com", uz: "your@email.com" },
  subscribe:     { en: "Subscribe",     bn: "সাবস্ক্রাইব",     az: "Abunə ol",    hi: "सब्सक्राइब", ky: "Жазылуу",       tg: "Обуна шудан",    uz: "Obuna boʻlish" },
  allRights:     { en: "All rights reserved.", bn: "সর্বস্বত্ব সংরক্ষিত।", az: "Bütün hüquqlar qorunur.", hi: "सर्वाधिकार सुरक्षित।", ky: "Бардык укуктар корголгон.", tg: "Ҳамаи ҳуқуқҳо ҳифз шудаанд.", uz: "Barcha huquqlar himoyalangan." },
  madeIn:        { en: "Made for the international community in Lithuania", bn: "লিথুয়ানিয়ার আন্তর্জাতিক কমিউনিটির জন্য তৈরি", az: "Litvadakı beynəlxalq icma üçün hazırlanıb", hi: "लिथुआनिया के अंतरराष्ट्रीय समुदाय के लिए बनाया गया", ky: "Литвадагы эл аралык жамаат үчүн жасалган", tg: "Барои ҷомеаи байналмилалӣ дар Литва сохта шудааст", uz: "Litvadagi xalqaro hamjamiyat uchun yaratilgan" },

  // ---------- Coming-soon placeholders ----------
  comingSoon:    { en: "Coming soon",                                                                bn: "শীঘ্রই আসছে",                                                              az: "Tezliklə",                                                              hi: "जल्द आ रहा है",                                                                  ky: "Жакында",                                                                tg: "Ба зудӣ",                                                                  uz: "Tez orada" },
  comingSoonDesc: { en: "This level is being prepared. A1 vocabulary is fully ready — try it now!",  bn: "এই স্তরটি প্রস্তুত করা হচ্ছে। A1 শব্দ ভাণ্ডার সম্পূর্ণ প্রস্তুত — এখনই চেষ্টা করুন!", az: "Bu səviyyə hazırlanır. A1 lüğəti tam hazırdır — indi sınayın!",         hi: "यह स्तर तैयार किया जा रहा है। A1 शब्दावली पूरी तरह तैयार है — अभी आज़माएँ!",       ky: "Бул деңгээл даярдалууда. A1 сөздүгү толук даяр — азыр сынап көрүңүз!", tg: "Ин сатҳ омода карда мешавад. Луғати A1 пурра тайёр аст — ҳозир санҷед!", uz: "Bu daraja tayyorlanmoqda. A1 lugʻati toʻliq tayyor — hozir sinab koʻring!" },
  tryA1:          { en: "Try A1",                                                                     bn: "A1 চেষ্টা করুন",                                                              az: "A1-i sınayın",                                                          hi: "A1 आज़माएँ",                                                                      ky: "A1 сынаңыз",                                                              tg: "A1-ро санҷед",                                                              uz: "A1 ni sinab koʻring" },

  // ---------- Phone / Email auth labels ----------
  phone:           { en: "Phone",            bn: "ফোন",                az: "Telefon",            hi: "फ़ोन",            ky: "Телефон",          tg: "Телефон",         uz: "Telefon" },
  phoneNumber:     { en: "Phone number",     bn: "ফোন নম্বর",          az: "Telefon nömrəsi",    hi: "फ़ोन नंबर",       ky: "Телефон номери",   tg: "Рақами телефон",  uz: "Telefon raqami" },
  enterPhone:      { en: "6XX XX XXX",       bn: "৬XX XX XXX",          az: "6XX XX XXX",         hi: "6XX XX XXX",     ky: "6XX XX XXX",        tg: "6XX XX XXX",      uz: "6XX XX XXX" },

  // ---------- Fundamentals page ----------
  fundamentalsHero:  { en: "The essential building blocks of Lithuanian.", bn: "লিথুয়ানিয়ান ভাষার মূল ভিত্তি।", az: "Litva dilinin əsas tikinti blokları.", hi: "लिथुआनियाई की आवश्यक बुनियादी बातें।", ky: "Литва тилинин негизги курулуш блоктору.", tg: "Қисмҳои асосии забони литвагӣ.", uz: "Litva tilining asosiy qurilish bloklari." },
  alphabetTab:       { en: "Alphabet & Pronunciation", bn: "বর্ণমালা ও উচ্চারণ",      az: "Əlifba və tələffüz",       hi: "वर्णमाला और उच्चारण",   ky: "Алфавит жана айтылыш",   tg: "Алифбо ва талаффуз",   uz: "Alifbo va talaffuz" },
  numbersTab:        { en: "Numbers",                  bn: "সংখ্যা",                az: "Rəqəmlər",                 hi: "संख्याएँ",              ky: "Сандар",                 tg: "Рақамҳо",               uz: "Raqamlar" },
  daysMonthsTab:     { en: "Days & Months",            bn: "দিন ও মাস",              az: "Günlər və aylar",          hi: "दिन और महीने",          ky: "Күндөр жана айлар",      tg: "Рӯзҳо ва моҳҳо",        uz: "Kunlar va oylar" },
  specialChars:      { en: "Special Characters",        bn: "বিশেষ অক্ষর",            az: "Xüsusi simvollar",         hi: "विशेष वर्ण",            ky: "Атайын белгилер",         tg: "Аломатҳои махсус",      uz: "Maxsus belgilar" },
  specialCharsDesc:  { en: "These unique Lithuanian letters need extra attention:", bn: "এই বিশেষ লিথুয়ানিয়ান অক্ষরগুলোতে বেশি মনোযোগ দিন:", az: "Bu unikal Litva hərfləri əlavə diqqət tələb edir:", hi: "इन विशेष लिथुआनियाई अक्षरों पर अतिरिक्त ध्यान दें:", ky: "Бул өзгөчө литва тамгалары көбүрөөк көңүл талап кылат:", tg: "Ин ҳарфҳои хоси литвагӣ диққати бештар талаб мекунанд:", uz: "Bu noyob litva harflari qoʻshimcha eʼtibor talab qiladi:" },
  fullAlphabet:      { en: "Full Alphabet",             bn: "সম্পূর্ণ বর্ণমালা",      az: "Tam əlifba",                hi: "पूर्ण वर्णमाला",        ky: "Толук алфавит",          tg: "Алифбои пурра",         uz: "Toʻliq alifbo" },
  letter:            { en: "Letter",                    bn: "অক্ষর",                  az: "Hərf",                     hi: "अक्षर",                ky: "Тамга",                   tg: "Ҳарф",                  uz: "Harf" },
  audio:             { en: "Audio",                     bn: "অডিও",                   az: "Səs",                       hi: "ऑडियो",                ky: "Үн",                      tg: "Аудио",                  uz: "Audio" },
  pronunciation:     { en: "Pronunciation",             bn: "উচ্চারণ",                 az: "Tələffüz",                  hi: "उच्चारण",               ky: "Айтылыш",                 tg: "Талаффуз",              uz: "Talaffuz" },
  sound:             { en: "Sound",                     bn: "ধ্বনি",                  az: "Səs",                       hi: "ध्वनि",                ky: "Үн",                      tg: "Овоз",                  uz: "Tovush" },
  daysOfWeek:        { en: "Days of the Week",          bn: "সপ্তাহের দিন",            az: "Həftənin günləri",          hi: "सप्ताह के दिन",         ky: "Жуманын күндөрү",         tg: "Рӯзҳои ҳафта",          uz: "Hafta kunlari" },
  monthsOfYear:      { en: "Months",                    bn: "মাসের নাম",               az: "Aylar",                     hi: "महीने",                 ky: "Айлар",                   tg: "Моҳҳо",                  uz: "Oylar" },
  fundamentalsAlphabetExplain: { en: "Lithuanian has 32 letters. Some special characters indicate unique sounds: ą, č, ę, ė, į, š, ų, ū, ž — these don't exist in English.", bn: "লিথুয়ানিয়ান বর্ণমালায় ৩২টি অক্ষর আছে। কিছু বিশেষ অক্ষর: ą, č, ę, ė, į, š, ų, ū, ž — এগুলো বাংলায় পাওয়া যায় না।", az: "Litva əlifbasında 32 hərf var. Bəzi xüsusi simvollar unikal səsləri ifadə edir: ą, č, ę, ė, į, š, ų, ū, ž.", hi: "लिथुआनियाई में 32 अक्षर हैं। कुछ विशेष अक्षर अनूठी ध्वनियाँ दर्शाते हैं: ą, č, ę, ė, į, š, ų, ū, ž।", ky: "Литва тилинде 32 тамга бар. Айрым атайын белгилер уникалдуу үндөрдү билдирет: ą, č, ę, ė, į, š, ų, ū, ž.", tg: "Алифбои литвагӣ 32 ҳарф дорад. Баъзе аломатҳои махсус овозҳои хосро ифода мекунанд: ą, č, ę, ė, į, š, ų, ū, ž.", uz: "Litva alifbosida 32 ta harf bor. Baʼzi maxsus belgilar noyob tovushlarni ifodalaydi: ą, č, ę, ė, į, š, ų, ū, ž." },
  fundamentalsNumbersExplain: { en: "Lithuanian numbers follow a logical pattern. Learn 1–10 first, then numbers like dvidešimt (twenty) make sense: dvi (two) + dešimt (ten).", bn: "লিথুয়ানিয়ান সংখ্যা একটি যৌক্তিক প্যাটার্ন অনুসরণ করে। আগে ১–১০ শিখুন, তারপর dvidešimt (২০) = dvi (২) + dešimt (১০)।", az: "Litva rəqəmləri məntiqi bir nümunəyə əsaslanır. Əvvəlcə 1–10-u öyrənin, sonra dvidešimt (iyirmi) = dvi (iki) + dešimt (on).", hi: "लिथुआनियाई संख्याएँ एक तार्किक पैटर्न का अनुसरण करती हैं। पहले 1–10 सीखें, फिर dvidešimt (बीस) = dvi (दो) + dešimt (दस)।", ky: "Литва сандары логикалык үлгүгө ылайык. Алгач 1–10 үйрөнүңүз, анан dvidešimt (жыйырма) = dvi (эки) + dešimt (он).", tg: "Рақамҳои литвагӣ як қолаби мантиқиро пайравӣ мекунанд. Аввал 1–10-ро омӯзед, баъд dvidešimt (бист) = dvi (ду) + dešimt (даҳ).", uz: "Litva raqamlari mantiqiy naqshga amal qiladi. Avval 1–10 ni oʻrganing, soʻng dvidešimt (yigirma) = dvi (ikki) + dešimt (oʻn)." },
  fundamentalsDaysExplain: { en: "Lithuanian days are based on numbers: pirmadienis = first day (Monday). The week starts on Monday in Lithuania.", bn: "লিথুয়ানিয়ান দিনের নাম সংখ্যা থেকে এসেছে: pirmadienis = প্রথম দিন (সোমবার)। লিথুয়ানিয়ায় সপ্তাহ সোমবার থেকে শুরু হয়।", az: "Litva günləri rəqəmlərə əsaslanır: pirmadienis = birinci gün (Bazar ertəsi). Litvada həftə Bazar ertəsindən başlayır.", hi: "लिथुआनियाई दिन संख्याओं पर आधारित हैं: pirmadienis = पहला दिन (सोमवार)।", ky: "Литва күндөрү сандарга негизделген: pirmadienis = биринчи күн (дүйшөмбү).", tg: "Рӯзҳои литвагӣ ба рақамҳо асос ёфтаанд: pirmadienis = рӯзи аввал (душанбе).", uz: "Litva kunlari raqamlarga asoslangan: pirmadienis = birinchi kun (dushanba)." },

  dontKnow:      { en: "Don't know",                bn: "জানি না",                     az: "Bilmirəm",              hi: "नहीं पता",          ky: "Билбейм",                tg: "Намедонам",             uz: "Bilmayman" },
  know:          { en: "Know",                      bn: "জানি",                       az: "Bilirəm",               hi: "पता है",            ky: "Билем",                  tg: "Медонам",               uz: "Bilaman" },
  flip:          { en: "Flip",                      bn: "উল্টান",                     az: "Çevir",                 hi: "पलटें",              ky: "Оодаруу",                tg: "Баргардондан",          uz: "Aylantirish" },
  clickToReveal: { en: "Click to reveal",           bn: "ক্লিক করুন প্রকাশ করতে",      az: "Açmaq üçün klikləyin",  hi: "खोलने के लिए क्लिक करें", ky: "Ачуу үчүн чыкылдатыңыз", tg: "Барои ошкор кардан клик кунед", uz: "Ochish uchun bosing" },
  saved:         { en: "Saved",                     bn: "সংরক্ষিত",                    az: "Yadda saxlanılıb",      hi: "सहेजा गया",          ky: "Сакталды",                tg: "Захира шуд",            uz: "Saqlandi" },
  saveAction:    { en: "Save",                      bn: "সংরক্ষণ",                     az: "Yadda saxla",           hi: "सहेजें",            ky: "Сактоо",                  tg: "Захира кунед",          uz: "Saqlash" },
  deckComplete:  { en: "Deck complete!",            bn: "ডেক শেষ হয়েছে!",            az: "Dəstə tamamlandı!",     hi: "डेक पूर्ण!",         ky: "Жыйнак аяктады!",         tg: "Даста ба итмом расид!", uz: "Toʻplam tugadi!" },
  toReview:      { en: "To review",                 bn: "পর্যালোচনার জন্য",           az: "Təkrar üçün",           hi: "समीक्षा के लिए",     ky: "Кайталоо үчүн",          tg: "Барои такрор",           uz: "Takrorlash uchun" },
  restart:       { en: "Restart",                   bn: "আবার শুরু",                  az: "Yenidən başla",         hi: "फिर शुरू",           ky: "Кайра баштоо",            tg: "Аз нав оғоз",           uz: "Qaytadan boshlash" },
  card:          { en: "Card",                      bn: "কার্ড",                      az: "Kart",                  hi: "कार्ड",              ky: "Карточка",                tg: "Корт",                  uz: "Karta" },
  gridView:      { en: "Grid",                      bn: "গ্রিড",                      az: "Şəbəkə",                hi: "ग्रिड",              ky: "Чарчы",                   tg: "Шабака",                uz: "Toʻr" },
  showExample:   { en: "Show example",              bn: "উদাহরণ দেখান",                az: "Nümunəni göstər",       hi: "उदाहरण दिखाएँ",     ky: "Мисалды көрсөтүү",        tg: "Мисолро нишон диҳед",   uz: "Misolni koʻrsatish" },
  hideExample:   { en: "Hide example",              bn: "উদাহরণ লুকান",                az: "Nümunəni gizlət",       hi: "उदाहरण छुपाएँ",      ky: "Мисалды жашыруу",         tg: "Мисолро пинҳон кунед",  uz: "Misolni yashirish" },
  knownCount:    { en: "known",                     bn: "জানা",                       az: "bilinən",               hi: "ज्ञात",             ky: "белгилүү",                tg: "донистагӣ",             uz: "ma'lum" },
  lines:         { en: "lines",                      bn: "লাইন",                       az: "sətir",                 hi: "पंक्तियाँ",          ky: "сап",                     tg: "сатр",                  uz: "qator" },
  dialogueWord:  { en: "Dialogue",                   bn: "সংলাপ",                       az: "Dialoq",                hi: "संवाद",             ky: "Диалог",                  tg: "Муколама",              uz: "Dialog" },
  dialoguesSub:  { en: "Real-life Lithuanian conversations with translations", bn: "বাস্তব লিথুয়ানিয়ান কথোপকথন অনুবাদসহ", az: "Tərcüməli real Litva söhbətləri", hi: "अनुवाद सहित वास्तविक लिथुआनियाई बातचीत", ky: "Котормосу менен реалдуу литва баарлашуулары", tg: "Сӯҳбатҳои воқеии литвагӣ бо тарҷума", uz: "Tarjimasi bilan haqiqiy litva suhbatlari" },
  grammarSub:    { en: "Essential A1 grammar with native-language explanations", bn: "মাতৃভাষায় ব্যাখ্যাসহ A1 ব্যাকরণ", az: "Ana dilində izahlarla əsas A1 qrammatikası", hi: "मातृभाषा में व्याख्या के साथ आवश्यक A1 व्याकरण", ky: "Эне тилдеги түшүндүрмөлөр менен A1 негизги грамматикасы", tg: "Грамматикаи асосии A1 бо шарҳҳо ба забони модарӣ", uz: "Ona tilidagi izohlar bilan asosiy A1 grammatikasi" },
} satisfies Record<string, Dict>;

export type TranslationKey = keyof typeof T;

export function t(key: TranslationKey, lang: UILanguage): string {
  const entry = T[key] as Partial<Record<UILanguage, string>> & { en: string };
  return entry[lang] ?? entry.en;
}
